recognize errors in pipes too
piped commands can lead to exit code 0 even though one or mulitple
commands within the pipe failed

since we use pipes in backup scripts (eg dump|zip|upload) we did not get
notifications on errors in the dump script (see example below)

example:

```
    :~ # pg_dumpall --foo
    pg_dumpall: unrecognized option '--foo'
    :~ # echo $?
    1
    :~ # pg_dumpall --foo|gzip
    pg_dumpall: unrecognized option '--foo'
    :~ # echo $?
    1
    :~ # pg_dumpall --foo|gzip|aws s3 cp - s3://bucket/foo.txt
    pg_dumpall: unrecognized option '--foo'
    :~ # echo $?
    0
```

diff --git a/docker/notify_if_fails b/docker/notify_if_fails
--- a/docker/notify_if_fails
+++ b/docker/notify_if_fails
@@ -8,7 +8,12 @@ then
   message="command '""$cmd""' failed"
 fi
 
-if ! bash -c "$cmd"
+# in case cmd uses pipes, capture any error within the pipe using pipefail
+# see https://stackoverflow.com/a/35465242
+bash -o pipefail -c "$cmd"
+
+# check for error (exit code != 0) and send slack notification
+if ! [ $? -eq 0 ]
 then
   slack chat send --channel "#sysadmin" --text "$message"
 fi
